#if !defined BOOTLOADER_COMMANDS_H
#define BOOTLOADER_COMMANDS_H

typedef enum {
	
	BL_GET_VER=0x51,
	BL_GET_HELP,
	BL_GET_CIP,
	BL_GET_RDP_STATUS,
	BL_GO_TO_ADDR,
	BL_FLASH_ERASE,
	BL_MEM_WRITE,
	BL_EN_RW_PROTECT,
	BL_MEM_READ,
	BL_READ_SECTOR_P_STATUS,
	BL_OTP_READ,
	BL_DIS_R_W_PROTECT
}bootloader_commands;

#endif